source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!

target 'EasyAttributes_Example' do
  pod 'EasyAttributes', :path => '../'

  target 'EasyAttributes_Tests' do
    inherit! :search_paths
  end

end
