coverage_service: cobertura_xml
workspace: Example/EasyAttributes.xcworkspace
xcodeproj: Example/EasyAttributes.xcodeproj
scheme: EasyAttributes-Example
source_directory: Classes/*
output_directory: Example/reports
ignore:
  - Example/Pods/*
