# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone 7'
    
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/EasyAttributes.xcworkspace -scheme EasyAttributes-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

after_success:
- slather
- bash <(curl -s https://codecov.io/bash) -t 39fa305b-9ca9-4222-aed6-e5129959d118 -f reports/cobertura.xml -X coveragepy -X gcov -X xcode