# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

osx_image: xcode10.1
env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone XR'
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone 7'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/EasyAttributes.xcworkspace -scheme EasyAttributes-Example -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
   
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/EasyAttributes.xcworkspace -scheme EasyAttributes-Example -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
- pod lib lint

after_success:
- slather
- bash <(curl -s https://codecov.io/bash) -t 39fa305b-9ca9-4222-aed6-e5129959d118 -f Example/reports/cobertura.xml -X coveragepy -X gcov -X xcode
